// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cglzrsorabappusuxavs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnbHpyc29yYWJhcHB1c3V4YXZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NzM0NTgsImV4cCI6MjA2OTM0OTQ1OH0.NInH6Or_hj2VBlZF2UkxgdI7IYwBU90vUU_12Oc91ic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});